version: '3'
services:
#mssql docker
  turistickaagencija-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - turistickaagencijanet

  turistickaagencija-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './TuristickaAgencija.WebAPI/TestImage:/app/TestImage'
    environment:
      - ConnectionStrings:TuristickaAgencija=Server=turistickaagencija-sql,1433;Database=DockerDatabase1;User=sa;Password=QWElkj132!;ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:5000
    networks:
      - turistickaagencijanet
    links:
      - turistickaagencija-sql
    depends_on:
      - turistickaagencija-sql
      
networks:
  turistickaagencijanet:
    driver: bridge