<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TuristickaAgencija.Model\TuristickaAgencija.Model.csproj" />
    <ProjectReference Include="..\TuristickaAgencija.Services\TuristickaAgencija.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Testna slika za seed podataka (kopira se i u bin i u docker image) -->
    <None Update="TestImage\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
