name: turisticka_agencija_mobile
description: "Turistička agencija - mobilna aplikacija za klijente."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5
  http: ^1.6.0
  # verziju odredjuje flutter_localizations (Flutter SDK)
  intl: any
  flutter_stripe: ">=11.0.0 <13.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
